# Generated by Django 5.2.7 on 2025-10-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='purchase_category',
            field=models.CharField(blank=True, choices=[('MATERIAL', 'Material'), ('TOOL', 'Tool'), ('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Vehicle'), ('SERVICE', 'Service'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
