# Generated by Django 5.2.7 on 2025-10-27 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('orders', '0003_order_assigned_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department associated with this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='departments.department'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='', help_text='Order description/purpose'),
        ),
    ]
