# Generated by Django 5.2.7 on 2025-10-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_notes_order_created_by_order_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_date',
            field=models.DateField(blank=True, help_text='Date when order was fulfilled/completed', null=True),
        ),
    ]
