# Generated by Django 5.2.7 on 2025-10-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_fulfillment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='expected_manufacturer',
            field=models.CharField(blank=True, help_text='Expected manufacturer for this line item', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='expected_mfr_part_no',
            field=models.CharField(blank=True, help_text='Expected manufacturer part number', max_length=500, null=True),
        ),
    ]
