# Generated by Django 5.2.7 on 2025-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('IN_SERVICE', 'In Service'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service'), ('RETIRED', 'Retired')], max_length=20),
        ),
    ]
