# Generated by Django 5.2.7 on 2025-10-20 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0002_initial'),
        ('orders', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('current_bin', models.ForeignKey(blank=True, db_column='current_bin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.bin')),
                ('current_location', models.ForeignKey(blank=True, db_column='current_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.location')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCalibrationSchedule',
            fields=[
                ('equipment', models.OneToOneField(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calibration_schedule', serialize=False, to='equipment.equipment')),
                ('calibration_interval_days', models.IntegerField(blank=True, null=True)),
                ('last_calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_calibration_schedule',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('equipment_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_no', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('default_service_interval_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_models',
                'indexes': [models.Index(fields=['manufacturer', 'model_no'], name='idx_equip_model_lookup')],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.ForeignKey(db_column='equipment_model_id', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instances', to='equipment.equipmentmodel'),
        ),
        migrations.CreateModel(
            name='EquipmentProcurement',
            fields=[
                ('equipment', models.OneToOneField(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='procurement', serialize=False, to='equipment.equipment')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_procurements', to='orders.order')),
                ('order_line', models.ForeignKey(db_column='order_line_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_procurements', to='orders.orderline')),
            ],
            options={
                'db_table': 'equipment_procurements',
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('equipment_assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='employees.employee')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.equipment')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='inventory.location')),
                ('work_order', models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='workorders.workorder')),
            ],
            options={
                'db_table': 'equipment_assignments',
                'indexes': [models.Index(fields=['equipment'], name='idx_eqa_equipment'), models.Index(fields=['employee'], name='idx_eqa_employee'), models.Index(fields=['location'], name='idx_eqa_location'), models.Index(fields=['work_order'], name='idx_eqa_wo'), models.Index(fields=['equipment', 'end_at'], name='idx_eqa_active_picker')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('equipment_maintenance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration'), ('REPAIR', 'Repair'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
                ('performed_by_employee', models.ForeignKey(blank=True, db_column='performed_by_employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_maintenance_performed', to='employees.employee')),
            ],
            options={
                'db_table': 'equipment_maintenance',
                'indexes': [models.Index(fields=['equipment'], name='idx_em_equipment')],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_model'], name='idx_equipment_model'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['current_location'], name='idx_equipment_loc'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['current_bin'], name='idx_equipment_bin'),
        ),
        migrations.AddIndex(
            model_name='equipmentprocurement',
            index=models.Index(fields=['order', 'order_line'], name='idx_equipment_po_line'),
        ),
    ]
