# Generated by Django 5.2.7 on 2025-10-21 00:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('equipment_assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'equipment_assignments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('equipment_maintenance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration'), ('REPAIR', 'Repair'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_maintenance',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('equipment_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_no', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('default_service_interval_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_models',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCalibrationSchedule',
            fields=[
                ('equipment', models.OneToOneField(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calibration_schedule', serialize=False, to='equipment.equipment')),
                ('calibration_interval_days', models.IntegerField(blank=True, null=True)),
                ('last_calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_calibration_schedule',
            },
        ),
        migrations.CreateModel(
            name='EquipmentProcurement',
            fields=[
                ('equipment', models.OneToOneField(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='procurement', serialize=False, to='equipment.equipment')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'equipment_procurements',
            },
        ),
    ]
