# Generated by Django 5.2.7 on 2025-10-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0001_initial'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_bin',
            field=models.ForeignKey(blank=True, db_column='current_bin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_location',
            field=models.ForeignKey(blank=True, db_column='current_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='locations.location'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='equipment',
            field=models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='locations.location'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='workorders.workorder'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='equipment',
            field=models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='performed_by_employee',
            field=models.ForeignKey(blank=True, db_column='performed_by_employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_maintenance_performed', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['manufacturer', 'model_no'], name='idx_equip_model_lookup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.ForeignKey(db_column='equipment_model_id', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instances', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='equipmentprocurement',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_procurements', to='orders.order'),
        ),
        migrations.AddField(
            model_name='equipmentprocurement',
            name='order_line',
            field=models.ForeignKey(db_column='order_line_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_procurements', to='orders.orderline'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['equipment'], name='idx_eqa_equipment'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['employee'], name='idx_eqa_employee'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['location'], name='idx_eqa_location'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['work_order'], name='idx_eqa_wo'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['equipment', 'end_at'], name='idx_eqa_active_picker'),
        ),
        migrations.AddIndex(
            model_name='equipmentmaintenance',
            index=models.Index(fields=['equipment'], name='idx_em_equipment'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_model'], name='idx_equipment_model'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['current_location'], name='idx_equipment_loc'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['current_bin'], name='idx_equipment_bin'),
        ),
        migrations.AddIndex(
            model_name='equipmentprocurement',
            index=models.Index(fields=['order', 'order_line'], name='idx_equipment_po_line'),
        ),
    ]
