# Generated by Django 5.2.7 on 2025-10-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
