# Generated by Django 5.2.7 on 2025-10-19 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0001_initial'),
        ('employees', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_no', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('default_service_interval_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], max_length=20)),
                ('purchased_at', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField()),
                ('current_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.bin')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
    ]
