# Generated by Django 5.2.7 on 2025-10-25 21:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0001_initial'),
        ('employees', '0001_initial'),
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], max_length=20)),
                ('purchased_at', models.DateTimeField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField()),
                ('current_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.bin')),
                ('current_location', models.ForeignKey(blank=True, db_column='current_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_no', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('default_service_interval_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolCalibrationSchedule',
            fields=[
                ('tool', models.OneToOneField(db_column='tool_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calibration_schedule', serialize=False, to='tools.tool')),
                ('calibration_interval_days', models.IntegerField()),
                ('last_calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tool_calibration_schedule',
            },
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolmodel'),
        ),
        migrations.CreateModel(
            name='ToolMaintenance',
            fields=[
                ('maintenance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration'), ('REPAIR', 'Repair'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by_employee', models.ForeignKey(blank=True, db_column='performed_by_employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_maintenance_performed', to='employees.employee')),
                ('tool', models.ForeignKey(db_column='tool_id', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='tools.tool')),
            ],
            options={
                'db_table': 'tool_maintenance',
                'indexes': [models.Index(fields=['tool'], name='idx_tm_tool')],
            },
        ),
        migrations.CreateModel(
            name='ToolProcurement',
            fields=[
                ('tool', models.OneToOneField(db_column='tool_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='procurement', serialize=False, to='tools.tool')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='tool_procurements', to='orders.order')),
                ('order_line', models.ForeignKey(db_column='order_line_id', on_delete=django.db.models.deletion.CASCADE, related_name='tool_procurements', to='orders.orderline')),
            ],
            options={
                'db_table': 'tool_procurements',
                'indexes': [models.Index(fields=['order', 'order_line'], name='idx_tool_po_line')],
            },
        ),
    ]
