# Generated by Django 5.2.7 on 2025-10-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='purchased_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='toolassignment',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='toolassignment',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
