# Generated by Django 5.2.7 on 2025-10-19 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_vendoritem_unique_together_and_more'),
        ('vendors', '0002_rename_contact_email_vendor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='inventory.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='vendors.vendor')),
                ('vendor_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_items', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Vendor Item',
                'verbose_name_plural': 'Vendor Items',
                'unique_together': {('vendor', 'item')},
            },
        ),
    ]
