# Generated by Django 5.2.7 on 2025-10-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturers', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sku', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='inventory.item')),
                ('mfr_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_items', to='manufacturers.manufacturerpart')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='vendors.vendor')),
                ('vendor_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_items', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Vendor Item',
                'verbose_name_plural': 'Vendor Items',
                'indexes': [models.Index(fields=['item'], name='idx_vendor_item_item_id'), models.Index(fields=['mfr_part'], name='idx_vendor_item_mfr_part')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'item'), name='unique_vendor_item'), models.UniqueConstraint(fields=('vendor', 'vendor_sku'), name='unique_vendor_sku_per_vendor')],
            },
        ),
    ]
