# Generated by Django 5.2.7 on 2025-10-21 20:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vendoritems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItemPriceHistory',
            fields=[
                ('price_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, help_text='Difference from previous price (positive = increase)', max_digits=10, null=True)),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from previous price', max_digits=6, null=True)),
                ('imported_by', models.ForeignKey(blank=True, db_column='imported_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_imports', to='users.user')),
                ('vendor_item', models.ForeignKey(db_column='vendor_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vendoritems.vendoritem')),
            ],
            options={
                'verbose_name': 'Vendor Item Price History',
                'verbose_name_plural': 'Vendor Item Price History',
                'db_table': 'vendor_item_price_history',
                'ordering': ['-effective_date', '-imported_at'],
                'indexes': [models.Index(fields=['vendor_item', '-effective_date'], name='idx_price_hist_item_date'), models.Index(fields=['effective_date'], name='idx_price_hist_date'), models.Index(fields=['imported_by'], name='idx_price_hist_user')],
            },
        ),
    ]
