# Generated by Django 5.2.7 on 2025-10-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_vendors_delete_vendoritem'),
        ('vendoritems', '0001_initial'),
        ('vendors', '0002_rename_contact_email_vendor_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendoritem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vendoritem',
            constraint=models.UniqueConstraint(fields=('vendor', 'item', 'vendor_sku'), name='unique_vendor_item_sku'),
        ),
    ]
