# Generated by Django 5.2.7 on 2025-10-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendoritems', '0002_vendoritempricehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorItemPriceHistory',
        ),
    ]
