# Generated by Django 5.2.7 on 2025-10-29 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_fulfillment_date'),
        ('vendoritems', '0003_delete_vendoritempricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItemPriceHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at this point in time', max_digits=10)),
                ('effective_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this price became effective')),
                ('notes', models.CharField(blank=True, help_text='Reason for price change or notes', max_length=500)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who triggered the price change (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_price_changes', to='orders.order')),
                ('vendor_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vendoritems.vendoritem')),
            ],
            options={
                'verbose_name': 'Vendor Item Price History',
                'verbose_name_plural': 'Vendor Item Price History',
                'db_table': 'vendor_item_price_history',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['vendor_item', '-effective_date'], name='idx_price_hist_vi_date'), models.Index(fields=['purchase_order'], name='idx_price_hist_po')],
            },
        ),
    ]
