# Generated by Django 5.2.7 on 2025-10-25 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('TRUCK', 'Truck'), ('JOB', 'Jobsite'), ('STORAGE', 'Storage')], max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
                'indexes': [models.Index(fields=['name', 'type'], name='idx_locations_name_type')],
            },
        ),
    ]
