# Generated by Django 5.2.7 on 2025-10-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
    ]
