# Generated by Django 5.2.7 on 2025-10-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
        ('vendoritems', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylayer',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_layers', to='orders.order'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_bin_movements', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, db_column='from_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='order_line',
            field=models.ForeignKey(blank=True, db_column='order_line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_bin_movements', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, db_column='to_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='jobs.workorder'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendors',
            field=models.ManyToManyField(related_name='items', through='vendoritems.VendorItem', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_layers', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemdefaultbin',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='itemdefaultbin',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemdefaultbin',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='itemlocationpolicy',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemlocationpolicy',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='itemlocationpolicy',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_policies', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='pendingallocation',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='pending_allocations', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='pendingallocation',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='pending_allocations', to='locations.location'),
        ),
        migrations.AddField(
            model_name='pendingallocation',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_allocations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='pendingallocation',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_allocations', to='jobs.workorder'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['location', 'bin_code'], name='uq_bins_per_location'),
        ),
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together={('location', 'bin_code')},
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['item', 'location', 'received_at'], name='idx_layer_fifo_lookup'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['item'], name='idx_layer_item'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['location'], name='idx_layer_location'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['received_at'], name='idx_layer_received'),
        ),
        migrations.AddIndex(
            model_name='itemdefaultbin',
            index=models.Index(fields=['item', 'location'], name='pk_item_default_bin'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdefaultbin',
            unique_together={('item', 'location')},
        ),
        migrations.AddIndex(
            model_name='itemlocationpolicy',
            index=models.Index(fields=['item', 'location'], name='pk_item_loc_policies'),
        ),
        migrations.AddIndex(
            model_name='itemlocationpolicy',
            index=models.Index(fields=['preferred_vendor'], name='idx_ilp_vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlocationpolicy',
            unique_together={('item', 'location')},
        ),
        migrations.AddIndex(
            model_name='pendingallocation',
            index=models.Index(fields=['item', 'status'], name='idx_pending_item_status'),
        ),
        migrations.AddIndex(
            model_name='pendingallocation',
            index=models.Index(fields=['work_order'], name='idx_pending_wo'),
        ),
        migrations.AddIndex(
            model_name='pendingallocation',
            index=models.Index(fields=['status'], name='idx_pending_status'),
        ),
        migrations.AddIndex(
            model_name='pendingallocation',
            index=models.Index(fields=['created_at'], name='idx_pending_created'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['g_code'], name='idx_item_gcode'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item'], name='idx_mov_item'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['moved_at'], name='idx_mov_time'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['work_order', 'total_cost'], name='idx_mov_work_order_cost'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['order', 'order_line'], name='idx_mov_order_line'),
        ),
    ]
