# Generated by Django 5.2.7 on 2025-10-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vendoritems', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendors',
            field=models.ManyToManyField(related_name='items', through='vendoritems.VendorItem', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemdefaultbin',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='itemdefaultbin',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemlocationpolicy',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemlocationpolicy',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_policies', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name', 'type'], name='idx_locations_name_type'),
        ),
        migrations.AddField(
            model_name='itemlocationpolicy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='itemdefaultbin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='bin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='itemlocationpolicy',
            index=models.Index(fields=['item', 'location'], name='pk_item_loc_policies'),
        ),
        migrations.AddIndex(
            model_name='itemlocationpolicy',
            index=models.Index(fields=['preferred_vendor'], name='idx_ilp_vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlocationpolicy',
            unique_together={('item', 'location')},
        ),
        migrations.AddIndex(
            model_name='itemdefaultbin',
            index=models.Index(fields=['item', 'location'], name='pk_item_default_bin'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdefaultbin',
            unique_together={('item', 'location')},
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['location', 'bin_code'], name='uq_bins_per_location'),
        ),
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together={('location', 'bin_code')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['g_code'], name='idx_item_gcode'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item'], name='idx_mov_item'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['moved_at'], name='idx_mov_time'),
        ),
    ]
