# Generated by Django 5.2.7 on 2025-10-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendoritem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendoritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vendoritem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendoritem',
            name='vendor_uom',
        ),
    ]
