# Generated by Django 5.2.7 on 2025-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_vendoritem_unique_together_and_more'),
        ('vendoritems', '0001_initial'),
        ('vendors', '0002_rename_contact_email_vendor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendors',
            field=models.ManyToManyField(related_name='items', through='vendoritems.VendorItem', to='vendors.vendor'),
        ),
        migrations.DeleteModel(
            name='VendorItem',
        ),
    ]
