# Generated by Django 5.2.7 on 2025-10-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('orders', '0005_add_fulfillment_date'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylayer',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Actual manufacturer of items in this layer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='manufacturer_part_no',
            field=models.CharField(blank=True, help_text='Manufacturer part number for items in this layer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', help_text='Vendor who supplied this inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_layers', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['vendor'], name='idx_layer_vendor'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['item', 'manufacturer'], name='idx_layer_item_mfr'),
        ),
    ]
