# Generated by Django 5.2.7 on 2025-10-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylayer_manufacturer_and_more'),
        ('vendoritems', '0004_vendoritempricehistory'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'subcategory'], name='idx_item_cat_subcat'),
        ),
    ]
