# Generated by Django 5.2.7 on 2025-10-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylayer_pendingallocation_and_more'),
        ('jobs', '0002_workorder'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='order_line',
            field=models.ForeignKey(blank=True, db_column='order_line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference code or identifier', max_length=100),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['order', 'order_line'], name='idx_mov_order_line'),
        ),
    ]
