# Generated by Django 5.2.7 on 2025-10-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_subcategory_item_idx_item_cat_subcat'),
        ('vendoritems', '0004_vendoritempricehistory'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='idx_item_cat_subcat',
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'subcategory', 'subcategory2', 'subcategory3'], name='idx_item_full_cat'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='idx_item_category'),
        ),
    ]
