# Generated by Django 5.2.7 on 2025-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_contact_email_vendor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('subcontractor', 'Subcontractor')], default='vendor', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
