# Generated by Django 5.2.7 on 2025-10-22 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.UUIDField(db_column='work_order_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wo_number', models.CharField(help_text='Work order number (unique per job)', max_length=120)),
                ('title', models.CharField(blank=True, help_text='Work order title/description', max_length=255)),
                ('status', models.CharField(default='DRAFT', help_text='Work order status', max_length=40)),
                ('scheduled_date', models.DateField(blank=True, help_text='When work is scheduled', null=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='departments.department')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_orders',
                'indexes': [models.Index(fields=['job', 'wo_number'], name='idx_wo_job_number'), models.Index(fields=['status'], name='idx_wo_status')],
                'unique_together': {('job', 'wo_number')},
            },
        ),
    ]
