# Generated by Django 5.2.7 on 2025-10-22 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.UUIDField(db_column='work_order_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wo_number', models.CharField(help_text='Work order number (unique per job)', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='jobs.job')),
            ],
            options={
                'db_table': 'work_orders',
            },
        ),
    ]