# Generated by Django 5.2.7 on 2025-10-19 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('jobs', '0001_initial'),
        ('workorders', '0002_alter_workorder_options_workorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='workorder',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='scheduled_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_number',
            field=models.CharField(default=0, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
