# Generated by Django 5.2.7 on 2025-10-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_workorder_options_remove_workorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='scheduled_date',
            field=models.DateField(null=True),
        ),
    ]
