# Generated by Django 5.2.7 on 2025-10-25 21:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PICKING', 'Picking'), ('STAGED', 'Staged'), ('PICKED_UP', 'Picked Up'), ('CANCELED', 'Canceled')], default='PICKING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('staged_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('staging_bin', models.ForeignKey(blank=True, db_column='staging_bin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_shipments', to='inventory.bin')),
                ('staging_location', models.ForeignKey(blank=True, db_column='staging_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_shipments', to='locations.location')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('shipment_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_to_ship', models.DecimalField(decimal_places=4, max_digits=14)),
                ('qty_picked', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('order_line', models.ForeignKey(db_column='order_line_id', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_lines', to='orders.orderline')),
                ('shipment', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shipments.shipment')),
            ],
            options={
                'db_table': 'shipment_lines',
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='idx_shipment_order'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='idx_shipment_status'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['staging_location'], name='idx_shipment_stage_loc'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['staging_bin'], name='idx_shipment_stage_bin'),
        ),
        migrations.AddIndex(
            model_name='shipmentline',
            index=models.Index(fields=['shipment'], name='idx_shipment_lines_shipment'),
        ),
        migrations.AddIndex(
            model_name='shipmentline',
            index=models.Index(fields=['order_line'], name='idx_shipment_lines_order_line'),
        ),
        migrations.AddConstraint(
            model_name='shipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'order_line'), name='uq_shipment_line'),
        ),
    ]
