# Generated by Django 5.2.7 on 2025-10-20 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerPart',
            fields=[
                ('mfr_part_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('upc', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='manufacturers.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemManufacturerPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_parts', to='inventory.item')),
                ('mfr_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manufacturerpart')),
            ],
        ),
        migrations.AddIndex(
            model_name='manufacturerpart',
            index=models.Index(fields=['manufacturer', 'part_number'], name='uq_mfr_part_per_mfr'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturerpart',
            unique_together={('manufacturer', 'part_number')},
        ),
        migrations.AddIndex(
            model_name='itemmanufacturerpart',
            index=models.Index(fields=['item', 'mfr_part'], name='pk_item_mfr_part'),
        ),
        migrations.AddIndex(
            model_name='itemmanufacturerpart',
            index=models.Index(fields=['item'], name='idx_item_mfr_lookup'),
        ),
        migrations.AlterUniqueTogether(
            name='itemmanufacturerpart',
            unique_together={('item', 'mfr_part')},
        ),
    ]
