# Generated by Django 5.2.7 on 2025-10-20 16:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.user')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['timestamp'], name='idx_audit_timestamp'), models.Index(fields=['user'], name='idx_audit_user'), models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity')],
            },
        ),
    ]
