# Generated by Django 5.2.7 on 2025-10-25 21:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
